### ISSUE TITLE
HiDPI support

### ISSUE THREAD

**Issue by ai** [Jeff2Ma/postcss-lazyimagecss#1]
Hi. Awesome plugin.

Maybe we should add retina/HiDPI support too?

`width: 16px → width: 8px`

**Comment by Jeff2Ma** [comment]
Hi, so happy to get a issue for the author of PostCSS!
In fact, this plugin already support  retina/HiDPI image. When you put the image file like`demo@2x.png`,  it will automatically half the size of `width` and `height` value and add `background-size` properties.

**Comment by ai** [comment]
Awesome!

Maybe we should add it to docs?

**Comment by Jeff2Ma** [comment]
Sure! Already update `README.md`!
